apiVersion: v1
kind: Pod
metadata:
  name: fastapiapp
  labels:
    app.kubernetes.io/name: fastapiapp
spec:
  containers:
  - name: fastapiapp
    image: sajjadhz/fastapiapp:latest
    ports:
      - containerPort: 8000
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app.kubernetes.io/name: fastapiapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc