apiVersion: v1
kind: Service
metadata:
  name: fastapiapp-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: fastapi
  ports:
    - name: http
      nodePort: 30007
      port: 80
      protocol: TCP
      targetPort: 8000

